---
- name: Prepare
  hosts: all
  tasks:
    - name: Update APT cache
      apt:
        cache_valid_time: 900
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Update Yum cache
      yum:
        update_cache: yes
      when: ansible_distribution in ["CentOS", "RedHat", "Fedora"]
      retries: 3
      delay: 5
